routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware'=>['web']], function (){
   Route::resource('blog','BlogController');
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $table='blog_post';

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Blog;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //show data
        $blogs = Blog::all();
        return view('blog.index',['blogs'=>$blogs]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //create new data
        return view('blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
       $this->validate($request,[
           'title'=> 'required',
           'description'=>'required',
       ]);

       //create new date
        $blog =new blog;
        $blog->title= $request->title;
        $blog->description = $request->description;
        $blog->save();
        return redirect()->route('blog.index')->with ('alter-success','Data hasbeen saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/blog/create.blade.php
@extends('master')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <h1>Create Data</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form class="" action="{{route('blog.store')}}" method="post" >
                {{csrf_field()}}
                <div class="form-group{{($errors->has('title')) ? $errors->first('title'): ''}}">
                    <input type="text" name="title" class="form-control" placeholder="Enter title Here">
                    {!! $errors->first('title','<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group{{($errors->has('description')) ? $errors->first('description'): ''}}">
                    <input type="text" name="description" class="form-control" placeholder="Enter Description Here">
                    {!! $errors->first('description','<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="save">
                </div>
            </form>
        </div>
    </div>
@stop

resources/views/blog/edit.blade.php
@extends('master')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <h1>Edit Data</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form class="" action="{{route('blog.update')}}" method="post" >
                
                {{csrf_field()}}
                <div class="form-group{{($errors->has('title')) ? $errors->first('title'): ''}}">
                    <input type="text" name="title" class="form-control" placeholder="Enter title Here">
                    {!! $errors->first('title','<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group{{($errors->has('description')) ? $errors->first('description'): ''}}">
                    <input type="text" name="description" class="form-control" placeholder="Enter Description Here">
                    {!! $errors->first('description','<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="save">
                </div>
            </form>
        </div>
    </div>
@stop

resources/views/blog/index.blade.php
@extends('master')
    @section('content')
        <div class="row">
            <div class="col-md-12">
                <h1>Simple Ajax CRUD</h1>
                <a href="{{route('blog.create')}}" class="btn btn-info pull-right">Create new Data</a><br>

            </div>
        </div>
        <div class="row">
            <table class="table table-striped">

                 <tr>
                    <th>No.</th>
                    <th>Title.</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>

            @foreach($blogs as $blog)
                    <tr>
                        <td>{{$blog->id}}</td>
                        <td>{{$blog->title}}</td>
                        <td>{{$blog->description}}</td>
                        <td>
                            <form  class="" action="{{route('blog.destroy',$blog->id)}}" method="post">
                                <input type="hidden" name="_method" value="delete">
                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                <a href="{{route('blog.edit',$blog->id)}}" class="btn btn-primary">Edit</a>
                                <input class="btn btn-danger" onclick="return confirm('Are you sure to delete this data')"; type="submit" name="_name" value="delete">
                            </form>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    @stop

resources/views/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ajax CRUD with Laravel 5.3</title>



    <link rel="stylesheet" href="{{asset('/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('/css/font-awesome.min.css')}}">




</head>

<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Ajax CRUD</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">HOME <span class="sr-only">(current)</span></a></li>
                <li><a href="#"></a></li>

            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
        <div class="container">
            <div class="row">
                @yield('content')
            </div>
        </div>

    <link rel="stylesheet" href="{{asset('/js/bootstrap.min.js')}}">
</body>
</html>